### ISSUE TITLE
为什么我用pip3 install flask_qiniustorage 会报错

### ISSUE THREAD

**Issue by yao631029659** [csuzhangxc/Flask-QiniuStorage#3]
```
 File "C:\Users\yao63\AppData\Local\Programs\Python\Python35-32\lib\site-packages\flask_qiniustorage.py", line 3, in <module>
    from urlparse import urljoin
ImportError: No module named 'urlparse'

```
使用的是python 3

**Comment by yao631029659** [comment]
改成这样就不会报错了
# -*- coding: utf-8 -*-
from urllib.parse import urljoin
import qiniu as QiniuClass


class Qiniu(object):
    def __init__(self, app=None):
        self.app = app
        if app is not None:
            self.init_app(app)

    def init_app(self, app):
        self._access_key = app.config.get('QINIU_ACCESS_KEY', '')
        self._secret_key = app.config.get('QINIU_SECRET_KEY', '')
        self._bucket_name = app.config.get('QINIU_BUCKET_NAME', '')
        domain = app.config.get('QINIU_BUCKET_DOMAIN')
        if not domain:
            self._base_url = 'http://' + self._bucket_name + '.qiniudn.com'
        else:
            self._base_url = 'http://' + domain

    # data是本地的文件名 filename是远程的文件名
    def save(self, data, filename=None):
        auth = QiniuClass.Auth(self._access_key, self._secret_key)
        # filename是远程地址 也叫做key
        token = auth.upload_token(self._bucket_name,filename,3600)
        return QiniuClass.put_file(token, filename, data)

    def delete(self, filename):
        auth = QiniuClass.Auth(self._access_key, self._secret_key)
        bucket = QiniuClass.BucketManager(auth)
        return bucket.delete(self._bucket_name, filename)

    def url(self, filename):
        return urljoin(self._base_url, filename)

**Comment by csuzhangxc** [comment]
当时写时没考虑Python3，感谢 yao631029659 指正。过几天方便时我更新一下pip
